/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import dao.*;
import entidades.*;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gabriel Cahng
 */
public class FrmCatalogo extends javax.swing.JInternalFrame {

    private String cod;
    
    DEditorial dEditorial = new DEditorial();
    ArrayList<Editorial> listaEditoriales = new ArrayList<>();
    
    TableRowSorter filtroTablaEditorial;
    
    /**
     * Creates new form FrmLibros
     */
    public FrmCatalogo() {
        initComponents();
        llenarTablaEditoriales();
    }

    private void limpiarEditorial() {
        this.TfCodEditorial.setText("");
        this.TfNomEditorial.setText("");
        this.TfCodEditorial.requestFocus();
    }
    
    private void actualizarTablaEditoriales() {
        llenarTablaEditoriales();
        this.TpLibros.setSelectedIndex(1);
        limpiarEditorial();
    }
    
    public void actualizarBotonesUD() {
        this.BtnAgregarEdit.setEnabled(true);
        this.BtnEliminarEdit.setEnabled(false);
        this.BtnEditarEdit.setEnabled(false);
        this.TfCodEditorial.setEnabled(true);
    }
    
    private void llenarListaEditoriales() {
        if(listaEditoriales.isEmpty())
            listaEditoriales.clear();
        
        listaEditoriales = dEditorial.listarEditorial();
    }
    
    private void llenarTablaEditoriales() {
        llenarListaEditoriales();
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String titulos[] = {"Código", "Nombre"};
        dtm.setColumnIdentifiers(titulos);
        
        for (Editorial e: listaEditoriales) {
            Object[] fila = new Object[] {
                e.getCod_editorial(),
                e.getNombre_editorial()
            };
            dtm.addRow(fila);
        }
        
        this.TblRegEditoriales.setModel(dtm);
    }
    
    private void filtrarTablaEditoriales() {
        filtroTablaEditorial.setRowFilter(RowFilter.regexFilter(this.TfDatoBuscarEdit.getText(),
                1));
    }
    
    private void verificarDatosVaciosEditorial() {
        if (this.TfCodEditorial.getText().equals("") || this.TfCodEditorial.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor verifique que el código" 
                + " no esté vacío.", "Editorial", JOptionPane.WARNING_MESSAGE);
            this.TfCodEditorial.requestFocus();
        }
        
        if (this.TfNomEditorial.getText().equals("") || this.TfNomEditorial.getText().length() == 0) {
            JOptionPane.showMessageDialog(this , "Por favor verifique que el nombre" 
                + " no esté vacío.", "Editorial", JOptionPane.WARNING_MESSAGE);
        }
        
        this.TfNomEditorial.requestFocus();
    }
    
    private void ubicarDatosEditorial() {
        int fila = this.TblRegEditoriales.getSelectedRow();
        cod = listaEditoriales.get(fila).getCod_editorial();
        
        this.TfCodEditorial.setEnabled(false);
        this.TfCodEditorial.setText(cod);
        
        this.TfNomEditorial.setText(listaEditoriales.get(fila).getNombre_editorial());
        
        this.BtnAgregarEdit.setEnabled(false);
        this.BtnEditarEdit.setEnabled(true);
        this.BtnEliminarEdit.setEnabled(true);
        this.TfNomEditorial.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblLibros = new javax.swing.JLabel();
        TpLibros = new javax.swing.JTabbedPane();
        PanelListadoAutores = new javax.swing.JPanel();
        PanelListadoEditoriales = new javax.swing.JPanel();
        LblBuscarEdit = new javax.swing.JLabel();
        TfDatoBuscarEdit = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblRegEditoriales = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        TfCodEditorial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TfNomEditorial = new javax.swing.JTextField();
        ToolbarCRUDEditorial = new javax.swing.JToolBar();
        BtnLimpiarEdit = new javax.swing.JButton();
        BtnAgregarEdit = new javax.swing.JButton();
        BtnEditarEdit = new javax.swing.JButton();
        BtnEliminarEdit = new javax.swing.JButton();
        PanelListadoClasificaciones = new javax.swing.JPanel();
        PanelListadoLibros = new javax.swing.JPanel();
        LblBuscarLibro = new javax.swing.JLabel();
        TfDatoLibro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRegistroLibros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Catálogo");

        LblLibros.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LblLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblLibros.setText("Listado de Catálogo");
        LblLibros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout PanelListadoAutoresLayout = new javax.swing.GroupLayout(PanelListadoAutores);
        PanelListadoAutores.setLayout(PanelListadoAutoresLayout);
        PanelListadoAutoresLayout.setHorizontalGroup(
            PanelListadoAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        PanelListadoAutoresLayout.setVerticalGroup(
            PanelListadoAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        TpLibros.addTab("Autores", PanelListadoAutores);

        LblBuscarEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblBuscarEdit.setText("Buscar: ");

        TfDatoBuscarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDatoBuscarEditActionPerformed(evt);
            }
        });
        TfDatoBuscarEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDatoBuscarEditKeyTyped(evt);
            }
        });

        TblRegEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblRegEditoriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblRegEditorialesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblRegEditoriales);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setText("Código: ");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("Nombre: ");

        ToolbarCRUDEditorial.setRollover(true);

        BtnLimpiarEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo-producto.png"))); // NOI18N
        BtnLimpiarEdit.setToolTipText("Limpiar");
        BtnLimpiarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiarEdit.setFocusable(false);
        BtnLimpiarEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLimpiarEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnLimpiarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarEditActionPerformed(evt);
            }
        });
        ToolbarCRUDEditorial.add(BtnLimpiarEdit);

        BtnAgregarEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disquete.png"))); // NOI18N
        BtnAgregarEdit.setToolTipText("Guardar");
        BtnAgregarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregarEdit.setFocusable(false);
        BtnAgregarEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAgregarEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAgregarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEditActionPerformed(evt);
            }
        });
        ToolbarCRUDEditorial.add(BtnAgregarEdit);

        BtnEditarEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        BtnEditarEdit.setToolTipText("Editar");
        BtnEditarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEditarEdit.setEnabled(false);
        BtnEditarEdit.setFocusable(false);
        BtnEditarEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEditarEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEditarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarEditActionPerformed(evt);
            }
        });
        ToolbarCRUDEditorial.add(BtnEditarEdit);

        BtnEliminarEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-eliminar.png"))); // NOI18N
        BtnEliminarEdit.setToolTipText("Eliminar");
        BtnEliminarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminarEdit.setEnabled(false);
        BtnEliminarEdit.setFocusable(false);
        BtnEliminarEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEliminarEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEliminarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarEditActionPerformed(evt);
            }
        });
        ToolbarCRUDEditorial.add(BtnEliminarEdit);

        javax.swing.GroupLayout PanelListadoEditorialesLayout = new javax.swing.GroupLayout(PanelListadoEditoriales);
        PanelListadoEditoriales.setLayout(PanelListadoEditorialesLayout);
        PanelListadoEditorialesLayout.setHorizontalGroup(
            PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoEditorialesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelListadoEditorialesLayout.createSequentialGroup()
                        .addComponent(LblBuscarEdit)
                        .addGap(2, 2, 2)
                        .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                            .addComponent(TfDatoBuscarEdit)))
                    .addGroup(PanelListadoEditorialesLayout.createSequentialGroup()
                        .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TfCodEditorial)
                            .addComponent(TfNomEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ToolbarCRUDEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PanelListadoEditorialesLayout.setVerticalGroup(
            PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoEditorialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBuscarEdit)
                    .addComponent(TfDatoBuscarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelListadoEditorialesLayout.createSequentialGroup()
                        .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TfCodEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(PanelListadoEditorialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TfNomEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ToolbarCRUDEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        TpLibros.addTab("Editoriales", PanelListadoEditoriales);

        javax.swing.GroupLayout PanelListadoClasificacionesLayout = new javax.swing.GroupLayout(PanelListadoClasificaciones);
        PanelListadoClasificaciones.setLayout(PanelListadoClasificacionesLayout);
        PanelListadoClasificacionesLayout.setHorizontalGroup(
            PanelListadoClasificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        PanelListadoClasificacionesLayout.setVerticalGroup(
            PanelListadoClasificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        TpLibros.addTab("Clasificaciones", PanelListadoClasificaciones);

        LblBuscarLibro.setText("Buscar:");

        TblRegistroLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblRegistroLibros);

        jLabel1.setText("ISBN:");

        jLabel2.setText("Titulo:");

        jLabel3.setText("MFN:");

        jLabel4.setText("Código Editorial:");

        jLabel5.setText("Código Clasificación:");

        jLabel6.setText("Código Autor:");

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo-producto.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disquete.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jToolBar2.setRollover(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-eliminar.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton4);

        javax.swing.GroupLayout PanelListadoLibrosLayout = new javax.swing.GroupLayout(PanelListadoLibros);
        PanelListadoLibros.setLayout(PanelListadoLibrosLayout);
        PanelListadoLibrosLayout.setHorizontalGroup(
            PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoLibrosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(PanelListadoLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelListadoLibrosLayout.createSequentialGroup()
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelListadoLibrosLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoLibrosLayout.createSequentialGroup()
                        .addComponent(LblBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(TfDatoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelListadoLibrosLayout.setVerticalGroup(
            PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfDatoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblBuscarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelListadoLibrosLayout.createSequentialGroup()
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelListadoLibrosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(PanelListadoLibrosLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelListadoLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TpLibros.addTab("Libros", PanelListadoLibros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(LblLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TpLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TpLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfDatoBuscarEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDatoBuscarEditKeyTyped
        // TODO add your handling code here:
        //filtrarTablaEditoriales();
        this.TfDatoBuscarEdit.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                filtrarTablaEditoriales();
                
            }
        });
        //this.TpLibros.setSelectedIndex(1);
        
        filtroTablaEditorial = new TableRowSorter(this.TblRegEditoriales.getModel());
        this.TblRegEditoriales.setRowSorter(filtroTablaEditorial);
    }//GEN-LAST:event_TfDatoBuscarEditKeyTyped

    private void BtnLimpiarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarEditActionPerformed
        // TODO add your handling code here:
        limpiarEditorial();
    }//GEN-LAST:event_BtnLimpiarEditActionPerformed

    private void BtnAgregarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEditActionPerformed
        // TODO add your handling code here:
        this.verificarDatosVaciosEditorial();
        
        try {
            Editorial e = new Editorial( 
                this.TfCodEditorial.getText(),
                this.TfNomEditorial.getText()
            );
            
            if (dEditorial.guardarEditorial(e)) {
                JOptionPane.showMessageDialog(this, "Registro Guardado.",
                        "Editorial", JOptionPane.INFORMATION_MESSAGE);
                
               
                actualizarTablaEditoriales();
                
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar",
                        "Editorial", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (HeadlessException ex) {
            System.out.println("Error al intentar guardar: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnAgregarEditActionPerformed

    private void TblRegEditorialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblRegEditorialesMouseClicked
        // TODO add your handling code here:
        
        this.TblRegEditoriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    ubicarDatosEditorial();
                }
            }
        });
    }//GEN-LAST:event_TblRegEditorialesMouseClicked

    private void BtnEditarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarEditActionPerformed
        // TODO add your handling code here:
        this.verificarDatosVaciosEditorial();
        
        Editorial e = new Editorial(
                this.TfCodEditorial.getText(),
                this.TfNomEditorial.getText()
        );
        
        if (dEditorial.editarEditorial(e)) {
            JOptionPane.showMessageDialog(this, "Registro Editado.",
                    "Editorial", JOptionPane.INFORMATION_MESSAGE);
            actualizarBotonesUD();
            actualizarTablaEditoriales();
            
        } else {
            JOptionPane.showMessageDialog(this, "Error al editar",
                    "Autor", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnEditarEditActionPerformed

    private void BtnEliminarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarEditActionPerformed
        // TODO add your handling code here:
        this.verificarDatosVaciosEditorial();
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Desea eliminar este registro?",
                "Editorial", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (resp == 0) {
            if (dEditorial.eliminarEditorial(cod)) {
                JOptionPane.showMessageDialog(this, "Registro eliminado satisfactoriamente",
                        "Editorial", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.",
                        "Editorial", JOptionPane.WARNING_MESSAGE);
            }
        }
        actualizarBotonesUD();
        actualizarTablaEditoriales();
    }//GEN-LAST:event_BtnEliminarEditActionPerformed

    private void TfDatoBuscarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDatoBuscarEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfDatoBuscarEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarEdit;
    private javax.swing.JButton BtnEditarEdit;
    private javax.swing.JButton BtnEliminarEdit;
    private javax.swing.JButton BtnLimpiarEdit;
    private javax.swing.JLabel LblBuscarEdit;
    private javax.swing.JLabel LblBuscarLibro;
    private javax.swing.JLabel LblLibros;
    private javax.swing.JPanel PanelListadoAutores;
    private javax.swing.JPanel PanelListadoClasificaciones;
    private javax.swing.JPanel PanelListadoEditoriales;
    private javax.swing.JPanel PanelListadoLibros;
    private javax.swing.JTable TblRegEditoriales;
    private javax.swing.JTable TblRegistroLibros;
    private javax.swing.JTextField TfCodEditorial;
    private javax.swing.JTextField TfDatoBuscarEdit;
    private javax.swing.JTextField TfDatoLibro;
    private javax.swing.JTextField TfNomEditorial;
    private javax.swing.JToolBar ToolbarCRUDEditorial;
    private javax.swing.JTabbedPane TpLibros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
