/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author Yamila Karim Conrado
 */
public class FrmPrincipal extends javax.swing.JFrame {
    //crear objeto formulario para cada uno (internos)
    FrmRegistroPersonas frmPersonas = new FrmRegistroPersonas();
    FrmCatalogo frmLibros = new FrmCatalogo();
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DpEscritorio = new javax.swing.JDesktopPane();
        MbMenu = new javax.swing.JMenuBar();
        MenuRH = new javax.swing.JMenu();
        MiGestionarPer = new javax.swing.JMenuItem();
        MenuCat = new javax.swing.JMenu();
        MiLibrosList = new javax.swing.JMenuItem();
        MiInventarioList = new javax.swing.JMenuItem();
        MenuPrestamos = new javax.swing.JMenu();
        MenuUser = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagina Principal");

        javax.swing.GroupLayout DpEscritorioLayout = new javax.swing.GroupLayout(DpEscritorio);
        DpEscritorio.setLayout(DpEscritorioLayout);
        DpEscritorioLayout.setHorizontalGroup(
            DpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        DpEscritorioLayout.setVerticalGroup(
            DpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        MenuRH.setText("RRHH");

        MiGestionarPer.setText("Gestionar Personas");
        MiGestionarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiGestionarPerActionPerformed(evt);
            }
        });
        MenuRH.add(MiGestionarPer);

        MbMenu.add(MenuRH);

        MenuCat.setText("Catalogo");

        MiLibrosList.setText("Listados Catalogo");
        MiLibrosList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiLibrosListActionPerformed(evt);
            }
        });
        MenuCat.add(MiLibrosList);

        MiInventarioList.setText("Listados Inventario");
        MiInventarioList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiInventarioListActionPerformed(evt);
            }
        });
        MenuCat.add(MiInventarioList);

        MbMenu.add(MenuCat);

        MenuPrestamos.setText("Prestamos");
        MbMenu.add(MenuPrestamos);

        MenuUser.setText("Usuarios");
        MbMenu.add(MenuUser);

        setJMenuBar(MbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiGestionarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiGestionarPerActionPerformed
        // TODO add your handling code here:
        // a ver cómo es esto XD
        this.DpEscritorio.add(this.frmPersonas);
        this.frmPersonas.setVisible(true);
    }//GEN-LAST:event_MiGestionarPerActionPerformed

    private void MiLibrosListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiLibrosListActionPerformed
        // TODO add your handling code here:
        this.DpEscritorio.add(this.frmLibros);
        this.frmLibros.setVisible(true);
    }//GEN-LAST:event_MiLibrosListActionPerformed

    private void MiInventarioListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiInventarioListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiInventarioListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DpEscritorio;
    private javax.swing.JMenuBar MbMenu;
    private javax.swing.JMenu MenuCat;
    private javax.swing.JMenu MenuPrestamos;
    private javax.swing.JMenu MenuRH;
    private javax.swing.JMenu MenuUser;
    private javax.swing.JMenuItem MiGestionarPer;
    private javax.swing.JMenuItem MiInventarioList;
    private javax.swing.JMenuItem MiLibrosList;
    // End of variables declaration//GEN-END:variables
}
