/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import dao.*;
import entidades.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gchang110101
 */
public class FrmPaginaPrincipal extends javax.swing.JInternalFrame {

    DPrestamo dprestamo = new DPrestamo();
    ArrayList<Prestamo> prestamos = new ArrayList<>();

     TableRowSorter filtroTablaPrestamosNombre;
    /**
     * Creates new form FrmPaginaPrincipal
     */
    public FrmPaginaPrincipal() {
        initComponents();
        llenarTablaPrestamos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblUAMLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRegistroPrestamos = new javax.swing.JTable();
        BtnAgregarPrestamo = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnCancelarPrestamo = new javax.swing.JButton();
        jTfFiltroNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnCompletarPrestamo = new javax.swing.JButton();

        setMaximizable(true);
        setResizable(true);
        setTitle("Pagina Principal");

        LblUAMLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/uamlogo (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel2.setText("Registro de Préstamos - UAM - Biblioteca Pablo Antonio Cuadra");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        TblRegistroPrestamos.setAutoCreateRowSorter(true);
        TblRegistroPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblRegistroPrestamos.getTableHeader().setReorderingAllowed(false);
        TblRegistroPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblRegistroPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblRegistroPrestamos);

        BtnAgregarPrestamo.setText("Agregar");
        BtnAgregarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarPrestamoActionPerformed(evt);
            }
        });

        BtnActualizar.setText("Actualizar");
        BtnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        BtnCancelarPrestamo.setText("Cancelar");
        BtnCancelarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelarPrestamo.setEnabled(false);

        jTfFiltroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfFiltroNombreActionPerformed(evt);
            }
        });
        jTfFiltroNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTfFiltroNombreKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nombre:");

        BtnCompletarPrestamo.setText("Completar");
        BtnCompletarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCompletarPrestamo.setEnabled(false);
        BtnCompletarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCompletarPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblUAMLogo)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnCancelarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(291, 291, 291)
                                    .addComponent(jLabel1)
                                    .addGap(70, 70, 70)
                                    .addComponent(jTfFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(115, 115, 115))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(jScrollPane1)))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnAgregarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(BtnCompletarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTfFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblUAMLogo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(BtnAgregarPrestamo)
                        .addGap(29, 29, 29)
                        .addComponent(BtnCompletarPrestamo)
                        .addGap(26, 26, 26)
                        .addComponent(BtnActualizar)
                        .addGap(0, 0, 0))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(BtnCancelarPrestamo)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfFiltroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfFiltroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfFiltroNombreActionPerformed

    private void BtnAgregarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarPrestamoActionPerformed
        // TODO add your handling code here:
        FrmLlenarDatosPrestamo frm = new FrmLlenarDatosPrestamo();
        frm.setVisible(true);

    }//GEN-LAST:event_BtnAgregarPrestamoActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        llenarTablaPrestamos();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void TblRegistroPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblRegistroPrestamosMouseClicked
        // TODO add your handling code here:
        BtnCompletarPrestamo.setEnabled(true);
    }//GEN-LAST:event_TblRegistroPrestamosMouseClicked

    private void BtnCompletarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCompletarPrestamoActionPerformed
        // TODO add your handling code here:
        int n = TblRegistroPrestamos.getSelectedRow();
        String codigo_prestamo = String.valueOf(TblRegistroPrestamos.getValueAt(n,0));
        System.out.println(codigo_prestamo);
        BigDecimal mora = BigDecimal.valueOf(Double.parseDouble(String.valueOf(TblRegistroPrestamos.getValueAt(n,7))));
        mora.setScale(2);
        prestamos = dprestamo.listarPrestamo();
        System.out.println("Tamaño de prestamos "+prestamos.size());
        Prestamo prestamo = new Prestamo();
        
        for(Prestamo p:prestamos){
            if(p.getCod_prestamo().equals(codigo_prestamo)){
                p.setMora(mora);
                prestamo = p;
                
            }
        }
        int resp = JOptionPane.showConfirmDialog(this, "¿Desea completar este préstamo?\nLa mora es "+mora,"Completar",JOptionPane.YES_NO_OPTION);
        if (resp == 0){
            //respuesta yes
            dprestamo.editarPrestamo(prestamo);
            JOptionPane.showMessageDialog(this, "Prestamo "+prestamo.getCod_prestamo(),"Prestamo "+prestamo.getCod_prestamo()+" completado",JOptionPane.INFORMATION_MESSAGE);
            llenarTablaPrestamos();
            BtnCompletarPrestamo.setEnabled(false);
            
        }
        else{
            //resp no
            System.out.println("Respuesta no");
            TblRegistroPrestamos.clearSelection();
            BtnCompletarPrestamo.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_BtnCompletarPrestamoActionPerformed

    private void jTfFiltroNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfFiltroNombreKeyTyped
        // TODO add your handling code here:
        this.jTfFiltroNombre.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                filtrarTablaPrestamos();

            }

            private void filtrarTablaPrestamos() {
                filtroTablaPrestamosNombre.setRowFilter(RowFilter.regexFilter("(?i)" + jTfFiltroNombre.getText(),
                1));
                
            }
        });

        filtroTablaPrestamosNombre = new TableRowSorter(this.TblRegistroPrestamos.getModel());
        this.TblRegistroPrestamos.setRowSorter(filtroTablaPrestamosNombre);
    }//GEN-LAST:event_jTfFiltroNombreKeyTyped

    private void llenarTablaPrestamos() {
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dtm = dprestamo.mostrarPrestamos();
        this.TblRegistroPrestamos.setModel(dtm);
    }
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregarPrestamo;
    private javax.swing.JButton BtnCancelarPrestamo;
    private javax.swing.JButton BtnCompletarPrestamo;
    private javax.swing.JLabel LblUAMLogo;
    private javax.swing.JTable TblRegistroPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTfFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
